import { createTheme } from '@shopify/restyle'

const bodyFontFamily =
  "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif"
const headingFontFamily = bodyFontFamily

const palette = {
  bgDark: '#09090b',
  bgElevatedDark: 'rgba(18, 18, 22, 0.85)',
  bgSoftDark: 'rgba(24, 24, 28, 0.74)',
  surfaceDark: 'rgba(255, 255, 255, 0.03)',
  surfaceStrongDark: 'rgba(255, 255, 255, 0.06)',
  borderDark: 'rgba(220, 38, 38, 0.25)',
  textDark: '#e4e4e7',
  textMutedDark: '#a1a1aa',
  titleDark: '#ffffff',
  accentDark: '#dc2626',
  accentStrongDark: '#ef4444',
  accentSoftDark: 'rgba(220, 38, 38, 0.15)',
  glowPrimaryDark: 'rgba(220, 38, 38, 0.15)',
  glowSecondaryDark: 'rgba(220, 38, 38, 0.05)',
  glowTertiaryDark: 'rgba(220, 38, 38, 0.1)',
  successDark: '#10b981',
  bgLight: '#d5dae1',
  bgElevatedLight: 'rgba(226, 231, 238, 0.72)',
  bgSoftLight: 'rgba(207, 214, 224, 0.7)',
  surfaceLight: 'rgba(52, 65, 85, 0.08)',
  surfaceStrongLight: 'rgba(0, 0, 0, 0.06)',
  borderLight: 'rgba(220, 38, 38, 0.15)',
  textLight: '#18181b',
  textMutedLight: '#52525b',
  titleLight: '#09090b',
  accentLight: '#b91c1c',
  accentStrongLight: '#dc2626',
  accentSoftLight: 'rgba(220, 38, 38, 0.1)',
  glowPrimaryLight: 'rgba(220, 38, 38, 0.15)',
  glowSecondaryLight: 'rgba(220, 38, 38, 0.05)',
  glowTertiaryLight: 'rgba(220, 38, 38, 0.1)',
  successLight: '#059669',
}

export const darkTheme = createTheme({
  colors: {
    bg: palette.bgDark,
    bgElevated: palette.bgElevatedDark,
    bgSoft: palette.bgSoftDark,
    surface: palette.surfaceDark,
    surfaceStrong: palette.surfaceStrongDark,
    border: palette.borderDark,
    text: palette.textDark,
    textMuted: palette.textMutedDark,
    title: palette.titleDark,
    accent: palette.accentDark,
    accentStrong: palette.accentStrongDark,
    accentSoft: palette.accentSoftDark,
    glowPrimary: palette.glowPrimaryDark,
    glowSecondary: palette.glowSecondaryDark,
    glowTertiary: palette.glowTertiaryDark,
    success: palette.successDark,
    gradientBorder: 'linear-gradient(140deg, rgba(220, 38, 38, 0.8), rgba(153, 27, 27, 0.4), rgba(220, 38, 38, 0.2))',
  },
  spacing: {
    none: 0,
    auto: 'auto',
    s: 8,
    m: 16,
    l: 24,
    xl: 40,
  },
  borderRadii: {
    md: 12,
    lg: 16,
    xl: 24,
  },
  breakpoints: {
    phone: 0,
    tablet: 768,
  },
  textVariants: {
    defaults: {
      color: 'text',
      fontFamily: bodyFontFamily,
      fontSize: 16,
      lineHeight: 24,
    },
    heading: {
      color: 'title',
      fontFamily: headingFontFamily,
      fontSize: 32,
      lineHeight: 38,
      letterSpacing: 0.5,
      textTransform: 'uppercase',
    },
    h1: {
      color: 'title',
      fontFamily: headingFontFamily,
      fontSize: 44,
      lineHeight: 50,
      fontWeight: '700',
      letterSpacing: 0.2,
    },
    h2: {
      color: 'title',
      fontFamily: headingFontFamily,
      fontSize: 36,
      lineHeight: 42,
      fontWeight: '700',
      letterSpacing: 0.15,
    },
    h3: {
      color: 'title',
      fontFamily: headingFontFamily,
      fontSize: 28,
      lineHeight: 34,
      fontWeight: '600',
      letterSpacing: 0.1,
    },
    h4: {
      color: 'title',
      fontFamily: headingFontFamily,
      fontSize: 22,
      lineHeight: 28,
      fontWeight: '600',
      letterSpacing: 0.1,
    },
    h5: {
      color: 'title',
      fontFamily: headingFontFamily,
      fontSize: 18,
      lineHeight: 24,
      fontWeight: '600',
      letterSpacing: 0.08,
    },
    h6: {
      color: 'title',
      fontFamily: headingFontFamily,
      fontSize: 16,
      lineHeight: 22,
      fontWeight: '600',
      letterSpacing: 0.05,
    },
    display: {
      color: 'title',
      fontFamily: headingFontFamily,
      fontSize: 44,
      lineHeight: 50,
      fontWeight: '700',
      letterSpacing: 0.2,
    },
    sectionTitle: {
      color: 'title',
      fontFamily: headingFontFamily,
      fontSize: 26,
      lineHeight: 32,
      fontWeight: '600',
      letterSpacing: 0.2,
    },
    subtitle: {
      color: 'text',
      fontFamily: bodyFontFamily,
      fontSize: 18,
      lineHeight: 27,
      fontWeight: '500',
    },
    body: {
      color: 'text',
      fontFamily: bodyFontFamily,
      fontSize: 16,
      lineHeight: 24,
    },
    bodySm: {
      color: 'text',
      fontFamily: bodyFontFamily,
      fontSize: 14,
      lineHeight: 21,
    },
    bodyMuted: {
      color: 'textMuted',
      fontFamily: bodyFontFamily,
      fontSize: 16,
      lineHeight: 24,
    },
    bodyMutedSm: {
      color: 'textMuted',
      fontFamily: bodyFontFamily,
      fontSize: 14,
      lineHeight: 21,
    },
    label: {
      color: 'accent',
      fontFamily: headingFontFamily,
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '700',
      letterSpacing: 1.5,
      textTransform: 'uppercase',
    },
    overline: {
      color: 'accent',
      fontFamily: headingFontFamily,
      fontSize: 12,
      lineHeight: 16,
      fontWeight: '700',
      letterSpacing: 2,
      textTransform: 'uppercase',
    },
    caption: {
      color: 'textMuted',
      fontFamily: bodyFontFamily,
      fontSize: 14,
      lineHeight: 20,
    },
    button: {
      color: 'title',
      fontFamily: headingFontFamily,
      fontSize: 14,
      lineHeight: 18,
      fontWeight: '600',
      letterSpacing: 0.5,
      textTransform: 'uppercase',
    },
    link: {
      color: 'accent',
      fontFamily: bodyFontFamily,
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '600',
    },
  },
})

export type ThemeType = typeof darkTheme

export const lightTheme = createTheme({
  ...darkTheme,
  colors: {
    ...darkTheme.colors,
    bg: palette.bgLight,
    bgElevated: palette.bgElevatedLight,
    bgSoft: palette.bgSoftLight,
    surface: palette.surfaceLight,
    surfaceStrong: palette.surfaceStrongLight,
    border: palette.borderLight,
    text: palette.textLight,
    textMuted: palette.textMutedLight,
    title: palette.titleLight,
    accent: palette.accentLight,
    accentStrong: palette.accentStrongLight,
    accentSoft: palette.accentSoftLight,
    glowPrimary: palette.glowPrimaryLight,
    glowSecondary: palette.glowSecondaryLight,
    glowTertiary: palette.glowTertiaryLight,
    success: palette.successLight,
    gradientBorder: 'linear-gradient(140deg, rgba(220, 38, 38, 0.8), rgba(153, 27, 27, 0.4), rgba(220, 38, 38, 0.2))',
  },
})
